#!/bin/sh
# Coto robi
# Autor 

# Jaki sposób sprawdzić czy łańuch znakowy jest liczą całkowita ?

error () { echo "$*" >&2 ; exit 1 ; }	# Komunikat na stderr

test_liczba () { # arg			# Test poprawnosci liczby # [+|-][0-9]*

  [ -z "$1" ] && error "pusty argument"

  # Wariant 0: z użyciem -eq
  [ "$1" -eq "$1" ] || error "$1 nie jest liczbą"

  # Wariant 1: z użyciem grep (man grep)
  echo $1 | grep -Eq '^[+|-]?[0-9]+$' || error "$1 nie jest liczbą"

  # Wariant 2: z użyciem case (man sh)  (tylko jedna cyfra!)
  case "$1" in
  [0-9]|-[0-9]|+[0-9]) return ;;	# OK
  esac
  error "$1 nie jest liczbą"
}

. ~/labsk/bin/konwersja-ip.sh

# START

echo "nazwa skryptu: $0"

echo "liczba argumentów: $#"

test_liczba $1

inet_ntoa $1

#test_liczba $2 
#test_abcd $2         # TODO  XXX ZZ ZZ

inet_aton $2

#EoF
# vim: set sw=4 ts=2 tw=78 expandtab :  # linia definuje głebokość i znak tabulacji
