# grep hosts: /etc/nsswitch.conf
Archlinux Server: hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
Archlinux GNOME	: hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns wins	# avahi running
Fedora 44	: hosts: files myhostname resolve [!UNAVAIL=return] dns							# avahi running
Ubuntu Desktop	: hosts: files mdns4_minimal [NOTFOUND=return] dns							# avahi running
Ubuntu Server	: hosts: files dns
